#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ActionBarPullToRefreshDemo.Resource", IsApplication=true)]

namespace ActionBarPullToRefreshDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_from_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_from_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out_to_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_out_to_top = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ptrAdapterViewBackground = 2130771984;
			
			// aapt resource value: 0x7f01000c
			public const int ptrAnimationStyle = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int ptrDrawable = 2130771974;
			
			// aapt resource value: 0x7f010012
			public const int ptrDrawableBottom = 2130771986;
			
			// aapt resource value: 0x7f010008
			public const int ptrDrawableEnd = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ptrDrawableStart = 2130771975;
			
			// aapt resource value: 0x7f010011
			public const int ptrDrawableTop = 2130771985;
			
			// aapt resource value: 0x7f010001
			public const int ptrHeaderBackground = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int ptrHeaderSubTextColor = 2130771971;
			
			// aapt resource value: 0x7f01000a
			public const int ptrHeaderTextAppearance = 2130771978;
			
			// aapt resource value: 0x7f010002
			public const int ptrHeaderTextColor = 2130771970;
			
			// aapt resource value: 0x7f01000e
			public const int ptrListViewExtrasEnabled = 2130771982;
			
			// aapt resource value: 0x7f010004
			public const int ptrMode = 2130771972;
			
			// aapt resource value: 0x7f010009
			public const int ptrOverScroll = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int ptrRefreshableViewBackground = 2130771968;
			
			// aapt resource value: 0x7f01000f
			public const int ptrRotateDrawableWhilePulling = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public const int ptrScrollingWhileRefreshingEnabled = 2130771981;
			
			// aapt resource value: 0x7f010005
			public const int ptrShowIndicator = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public const int ptrSubHeaderTextAppearance = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060003
			public const int header_footer_left_right_padding = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int header_footer_top_bottom_padding = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int indicator_corner_radius = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int indicator_internal_padding = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int indicator_right_padding = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int default_ptr_flip = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int default_ptr_rotate = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int indicator_arrow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int indicator_bg_bottom = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int indicator_bg_top = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int MyButton = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int both = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int disabled = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int fl_inner = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int flip = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int gridview = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int manualOnly = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int pullDownFromTop = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int pullFromEnd = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int pullFromStart = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int pullUpFromBottom = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int pull_refresh_scrollview = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int pull_to_refresh_image = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int pull_to_refresh_progress = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int pull_to_refresh_sub_text = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int pull_to_refresh_text = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int rotate = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int scrollview = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int webview = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int common_pull_down_list_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int pull_to_refresh_header_horizontal = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int pull_to_refresh_header_vertical = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070007
			public const int ApplicationName = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int Hello = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int pull_to_refresh_from_bottom_pull_label = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int pull_to_refresh_from_bottom_refreshing_label = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int pull_to_refresh_from_bottom_release_label = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int pull_to_refresh_pull_label = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int pull_to_refresh_refreshing_label = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int pull_to_refresh_release_label = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefresh = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 16
			public const int PullToRefresh_ptrAdapterViewBackground = 16;
			
			// aapt resource value: 12
			public const int PullToRefresh_ptrAnimationStyle = 12;
			
			// aapt resource value: 6
			public const int PullToRefresh_ptrDrawable = 6;
			
			// aapt resource value: 18
			public const int PullToRefresh_ptrDrawableBottom = 18;
			
			// aapt resource value: 8
			public const int PullToRefresh_ptrDrawableEnd = 8;
			
			// aapt resource value: 7
			public const int PullToRefresh_ptrDrawableStart = 7;
			
			// aapt resource value: 17
			public const int PullToRefresh_ptrDrawableTop = 17;
			
			// aapt resource value: 1
			public const int PullToRefresh_ptrHeaderBackground = 1;
			
			// aapt resource value: 3
			public const int PullToRefresh_ptrHeaderSubTextColor = 3;
			
			// aapt resource value: 10
			public const int PullToRefresh_ptrHeaderTextAppearance = 10;
			
			// aapt resource value: 2
			public const int PullToRefresh_ptrHeaderTextColor = 2;
			
			// aapt resource value: 14
			public const int PullToRefresh_ptrListViewExtrasEnabled = 14;
			
			// aapt resource value: 4
			public const int PullToRefresh_ptrMode = 4;
			
			// aapt resource value: 9
			public const int PullToRefresh_ptrOverScroll = 9;
			
			// aapt resource value: 0
			public const int PullToRefresh_ptrRefreshableViewBackground = 0;
			
			// aapt resource value: 15
			public const int PullToRefresh_ptrRotateDrawableWhilePulling = 15;
			
			// aapt resource value: 13
			public const int PullToRefresh_ptrScrollingWhileRefreshingEnabled = 13;
			
			// aapt resource value: 5
			public const int PullToRefresh_ptrShowIndicator = 5;
			
			// aapt resource value: 11
			public const int PullToRefresh_ptrSubHeaderTextAppearance = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
